// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5Qu2Ha7YZFkVkoWERDeVN9dZvIwq6uNA',
    appId: '1:1050952478395:web:34dfba9b4530f5a05a439e',
    messagingSenderId: '1050952478395',
    projectId: 'gastapp-847f9',
    authDomain: 'gastapp-847f9.firebaseapp.com',
    storageBucket: 'gastapp-847f9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH-PMbO4jh6jg4mr-OOmlzIoI4FN-fA1k',
    appId: '1:1050952478395:android:e347a4500c7e74a35a439e',
    messagingSenderId: '1050952478395',
    projectId: 'gastapp-847f9',
    storageBucket: 'gastapp-847f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6Bih0jtjzuUSYPyKctRlIcVXlx4yjtlM',
    appId: '1:1050952478395:ios:a98dd41a4897610b5a439e',
    messagingSenderId: '1050952478395',
    projectId: 'gastapp-847f9',
    storageBucket: 'gastapp-847f9.appspot.com',
    iosBundleId: 'com.example.gastapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6Bih0jtjzuUSYPyKctRlIcVXlx4yjtlM',
    appId: '1:1050952478395:ios:a98dd41a4897610b5a439e',
    messagingSenderId: '1050952478395',
    projectId: 'gastapp-847f9',
    storageBucket: 'gastapp-847f9.appspot.com',
    iosBundleId: 'com.example.gastapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5Qu2Ha7YZFkVkoWERDeVN9dZvIwq6uNA',
    appId: '1:1050952478395:web:8ae90792a99ee50f5a439e',
    messagingSenderId: '1050952478395',
    projectId: 'gastapp-847f9',
    authDomain: 'gastapp-847f9.firebaseapp.com',
    storageBucket: 'gastapp-847f9.appspot.com',
  );
}
